name: test_web_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_bloc: ^8.1.4
  equatable: ^2.0.0
  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  go_router: ^14.8.1
  dio: ^5.8.0+1
  get_it: ^8.0.3
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1

  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
flutter:
  assets:
    - assets/icons/
    - assets/images/
  uses-material-design: true

